### ISSUE TITLE
Fundamental issue in the authorship statement

### ISSUE THREAD

**Issue by erkinalp** [daveshap/HeuristicImperatives#1]
https://github.com/daveshap/HeuristicImperatives/blob/main/Heuristic%20Imperatives.pdf says most of it is authored by AI with no human editing. Most jurisdictions (the UK is a notable exception here) consider such stuff uncopyrightable. To avoid doubt and prevent the work from uncopyrightable in its entirety, contributions of you and the GPT-4 should be clearly denoted

**Comment by daveshap** [comment]
...copyright does not matter in the least?
