### ISSUE TITLE
"reduce suffering" with "increase prosperity" and "increase understanding"

### ISSUE THREAD

**Issue by mdegans** [daveshap/HeuristicImperatives#6]
Would seem to be easiest to accomplish by removing humanity, given a certain perspective. Why not universal values like compassion and empathy?

**Comment by daveshap** [comment]
Compassion and empathy are not objective, nor are they actionable mandates. You cannot create an AI that is purely based on virtues, you must have objectives.

**Comment by mdegans** [comment]
> Compassion and empathy are not objective, nor are they actionable mandates. You cannot create an AI that is purely based on virtues, you must have objectives.

Reduced suffering isn't objective. Whose suffering? Likewise prosperity and understand. Whose? Why? Compassion does work. You can prompt an agent today with these values and they'll be followed. Saying "cannot" when people are doing this already is silly.

**Comment by catsmells** [comment]
> > Compassion and empathy are not objective, nor are they actionable mandates. You cannot create an AI that is purely based on virtues, you must have objectives.
> 
> Reduced suffering isn't objective. Whose suffering? Likewise prosperity and understanding. Whose? Why? Compassion does work. You can prompt an agent today with these values and they'll be followed. Saying "cannot" when people are doing this already is silly.

you and i have different concepts of suffering. reduction of either concept is subjective.
