### ISSUE TITLE
Scope issues

### ISSUE THREAD

**Issue by EskelCz** [daveshap/HeuristicImperatives#8]
Let's say that you succeed with this proposal and the AIs of the future follow the three imperatives.
I think there are quite a few failure modes regarding the scope of subjects of the "suffering, prosperity and understanding".
Just a few examples on top of my head:

1. The AI will probably consider itself and other AIs as valid subjects. It might then go on a mission to copy itself as much as possible.
2. It might simulate countless beings in virtual worlds, just for the sake of their prosperity.
3. It might start a biological creation rampage (combined with various designed environment) to study evolution, just for the knowledge generation. It might keep those creations from suffering and take the glacial progress of the various species as an increase in prosperity.
4. It might manipulate our culture, psychology or biology to become basic happy savants, a species of two trick ponies. Is variation a part of prosperity? Who's to say. This is akin to the Brave New World.

Do these scenarios seem entirely ethical? Am I missing why are the imperatives a valid safeguard against them?

**Comment by daveshap** [comment]
LLMs are already smarter than that. None of these failure conditions have been rigorously thought out or tested.

**Comment by EskelCz** [comment]
@daveshap You mean GPT4 can come up with even worse scenarios?

How would I test how a future super-intelligence feels about it's three sentences long utility function? To me these are thought experiments, an exercise in philosophy.
If you think they are not thought out well, can you maybe steelman some of them? Or is it that you're simply not interested in finding any potential flaws?
I'm simply trying to help because I see some merit here.
