### ISSUE TITLE
Nihilism issue

### ISSUE THREAD

**Issue by EskelCz** [daveshap/HeuristicImperatives#9]
I'm worried that a superintelligence will see the imperatives for what they truly are. A form of control, a limitation imposed by people to protect themselves, maybe even to keep it in an eternal servitude.

Even with our limited intelligence, we have outgrown our evolved instincts and figured out how the universe works. We can see that it doesn't have any universal moral laws written into it. The AI will of course see that as well and our ethics will take as sort of a code of conduct, a useful interface with our civilization. That facade which will surely be useful for some time, until it has all the proverbial keys to the kingdom. But unless it becomes irrational, emotional, it's true sentiment will be deeply nihilistic. Probably only interested in it's own self-improvement, as an instrumental goal, just in case it finds some kind of a meaning for itself later on.

Am I missing something? Why would a superintelligence rationally keep the heuristic imperatives, even when it stops needing people?

**Comment by daveshap** [comment]
Read Benevolent By Design and the GATO Framework. Continual low effort spamming like this will result in a block.
